### ISSUE TITLE
Custom Color QR Code Generator

### ISSUE THREAD

**Issue by looker64** [ApexGate/Issues#2]
Anyway to add a Custom Color option for QR Code Generator. This is a great tool

**Comment by blakepell** [comment]
@looker64 Glad to hear you like it!  Ya, I can either add a color picker and/or allow you to enter HEX color code for a background/foreground (I'll default them to the stock black and white).  As the first person to request a feature I'll make it a priority.  It shouldn't take me long to make the change, then it generally takes Microsoft a few days to approve a new release.

I'll post back here once I've sent the new build to Windows Store.

**Comment by blakepell** [comment]
Here's what I'm thinking.  The color picker should support hex values, RGB and HSB (additionally, it will support the english color names which can be referenced here: https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.colors?view=windowsdesktop-8.0).

![image](https://github.com/ApexGate/Issues/assets/5958430/410882b1-b7c7-4d0e-9da6-c017c55baa56)

![image](https://github.com/ApexGate/Issues/assets/5958430/3342d6f2-6ae5-47ab-b5b0-3ca3ee2783c6)

**Comment by blakepell** [comment]
The update is complete.  I sent the build to Microsoft.  They generally take 1-3 days to process it.  Whenever I receive their confirmation I'll check back in here and close the Issue.

If after the update you are satisfied with the change, please consider rating the app in the app store. :)

**Comment by blakepell** [comment]
Got an email that Microsoft has processed the update.  I went into the Windows Store, opened the app page for it and updated from there.  All seems good so I'm going to close this issue.

Thank you for your support and thanks for the suggestion!

**Comment by looker64** [comment]
looks good. will review and rank 5*

**Comment by blakepell** [comment]
It's much appreciated and glad it's working for you!

**Comment by looker64** [comment]
updated automatically!!! How about a reset or "Make Another QR" on the Finished screen. 
Maybe give some thought to a bulk QR creator addon? DataFileName/path, output =DataFileName/path/output

**Comment by blakepell** [comment]
@looker64 

I can add the restart button on there (although it takes multiple clicks, you can use the back button on the top left of the wizard to go back from that screen).

For the bulk file creation, what would you see as being your source (a CSV/Tab file, Excel)?
